name: hmm-tagger
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - jupyter
  - nb_conda
  - nltk
  - pandas
  - pomegranate
  - pydot
  - pydotplus
  - scikit-learn
  - scipy
  - tqdm
  - pip
  - pip:
    - udacity-pa>=0.2